apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  labels:
    app: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: watcher
          image: 002665144501.dkr.ecr.eu-central-1.amazonaws.com/bf-senthu-test:test6
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: watcher
  annotations:
    prometheus.io/port: "5000"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: watcher
  ports:
    - protocol: TCP
      port: 5000
      name: http-metrics
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-watcher
  labels:
    app: watcher
spec:
  jobLabel: app
  selector:
    matchExpressions:
    - {key: app, operator: Exists}
  namespaceSelector:
    matchNames:
    - kube-system
    - default
  endpoints:
  - port: http-metrics
    interval: 10s